[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/decap-cms"

[params.decap_cms._preview_style_partials.hb]
path = "hb/assets/css-resource"

[params.decap_cms._configs.hb_field_featured.fields.featured]
default = false
widget = "boolean"
name = "featured"
label = "Featured"
i18n = true
required = false

[params.decap_cms._configs.hb_field_pinned.fields.pinned]
default = false
widget = "boolean"
name = "pinned"
label = "Pinned"
i18n = true
required = false
