[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/decap-cms"

[params.decap_cms._preview_style_partials.hb]
path = "hb/assets/css-resource"

[params.decap_cms._configs.hb_field_comments.fields.comments]
default = false
widget = boolean
name = "comments"
label = "Allow comments on post"
i18n = true
required = false
default = true

[params.decap_cms._configs.hb_field_featured.fields.featured]
default = false
widget = "boolean"
name = "featured"
label = "Featured"
i18n = true
required = false
label = "Feature post in carousel"

[params.decap_cms._configs.hb_field_pinned.fields.pinned]
default = false
widget = "boolean"
name = "pinned"
label = "Pinned"
i18n = true
required = false
label = "Pin post on front page and in carousel"
