[[module.imports]]
path = "github.com/hbstack/decap-cms"

[params.hugopress.modules.decap-cms-netlify-identity.hooks.head-end]

[params.hugopress.modules.decap-cms-netlify-identity.hooks.body-end]

[params.decap_cms._admin]
path = "/admin/"

[params.decap_cms._netlify_identity]
url = "https://identity.netlify.com/v1/netlify-identity-widget.js"
